### ISSUE TITLE
XMR or other contribution method?

### ISSUE THREAD

**Issue by PaulSpoerry** [JohannesPertl/vreddit-download-bot#1]
Hate PayPal... this is awesome though. Even if it's $5USD for a beer/coffee would it be possible to donate in a way other than PayPal?

**Comment by JohannesPertl** [comment]
First of all, thank you very much! 
I chose PayPal for the donation link, because its the most popular payment method, but I actually prefer crypto currency myself. 
I mostly use Nano, but wanted to try out Monero anyway, so I just created a wallet :)

Monero: 87dUEeNBM3rBAgs592cU5o6FhoMgyXqECc99v3A3jJktCgad42wEZBwh48c6NmX9ghXkmk9sQYNFZByw5qSdxuvcCDWHeZr

Nano: nano_1bfxis85pgh3wjxete59mbgaarjzdwrqqgojohtupwc9an4pgcb8wqr89gbg

Ethereum: 0x9D25F8d8471322b8b26dc0EE028D158EA34bFC2D
