### ISSUE TITLE
Error when starting bot

### ISSUE THREAD

**Issue by compi2k** [JohannesPertl/vreddit-download-bot#21]
I get this error:

`pi@himbeere:~/vreddit-download-bot $ python3 -i bot.py
Authenticating...

Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 845, in items
    d.update(self._sections[section])
KeyError: 'vreddit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 272, in <module>
    main()
  File "bot.py", line 29, in main
    reddit = authenticate()
  File "bot.py", line 102, in authenticate
    reddit = praw.Reddit('vreddit', user_agent='vreddit')
  File "/home/pi/.local/lib/python3.7/site-packages/praw/reddit.py", line 189, in __init__
    config_section, config_interpolation, **config_settings
  File "/home/pi/.local/lib/python3.7/site-packages/praw/config.py", line 82, in __init__
    self.custom = dict(Config.CONFIG.items(site_name), **settings)
  File "/usr/lib/python3.7/configparser.py", line 848, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'vreddit'
You provided the name of a praw.ini configuration which does not exist.

For help with creating a Reddit instance, visit
https://praw.readthedocs.io/en/latest/code_overview/reddit_instance.html

For help on configuring PRAW, visit
https://praw.readthedocs.io/en/latest/getting_started/configuration.html
>>>`

Is this a error on my site?

**Comment by JohannesPertl** [comment]
You need to fill in your own bot information in the [praw.ini](https://github.com/JohannesPertl/vreddit-download-bot/blob/master/praw.ini) file. In my case, I identify my bot as 'vreddit', while in your case, you need to choose an own identifier instead of 'ExampleBot'.

You should also change the user_agent in the authenticate() method to something different. You can read more about it [here](https://praw.readthedocs.io/en/latest/getting_started/quick_start.html)

**Comment by compi2k** [comment]
Which kind of app do I have to create on reddit? I put everything in correctly. Still won't work.
I still don't understand what you are meaning with authenticate()

**Comment by JohannesPertl** [comment]
Send me a message on Discord to Marvin#7307 and I'll explain the details
